WIP Perfomance recovery through caching supported apps
natanjunges/deb-get pull request #14
Opened 2022-11-10 00:28 UTC by philclifford

`deb-get list` without parameters will use a cache files if present (or create them if not) to regain the performance lost in checking every time.

Todo:
 - [ ] Maintain the cache during install/remove
 - [ ] Update the cache when  update of repos occurs (can just be rm and let the user re-create the cache on first miss)

2022-11-10 04:32 UTC, philclifford commented
BTW the errors in test will be because of missing fixes to apps.

2022-11-14 15:37 UTC, natanjunges requested changes

2022-11-14 15:37 UTC, natanjunges commented on deb-get
> +function fast_list() {
Unused. Please remove.

2022-11-14 15:37 UTC, natanjunges commented on deb-get
> +        ${ELEVATE} rm -f ${CACHE_DIR}/supported.list  ${CACHE_DIR}/supported_apps.list
Instead of just removing them, it should regenerate them (calling `list_debs` and saving to files), since `list` can't.

2022-11-14 15:37 UTC, natanjunges commented on deb-get
> +            local sscmd=$(echo ${ELEVATE} sed -i -e \'\/^${APP}$\/d\' ${CACHE_DIR}/supported.list)
Why not simply run the line?

2022-11-14 18:12 UTC, philclifford commented on deb-get
> +            local sscmd=$(echo ${ELEVATE} sed -i -e \'\/^${APP}$\/d\' ${CACHE_DIR}/supported.list)
because I was tired and could not get away from
```
sed: -e expression #1, char 1: unknown command: `''
```
So worked around my tiredness.  Apparently having covid-induced brain-fog actually improves my coding since today it was easy but then it was hours of  silently screaming "but why?" :shrug:

2022-11-14 20:33 UTC, philclifford commented on deb-get
> +        else
Sorted

2022-11-14 21:49 UTC, natanjunges requested changes

2022-11-14 21:49 UTC, natanjunges commented on deb-get
> +    if [ ${SOMETHING} == "Changed" ] || [ ! -z ${FORCE_CACHE_UPDATE} ]  || [ ! -f  ${CACHE_DIR}/supported_apps.list ]; then
Is `FORCE_CACHE_UPDATE` something you left behind?

2022-11-15 02:55 UTC, philclifford commented on deb-get
> +    if [ ${SOMETHING} == "Changed" ] || [ ! -z ${FORCE_CACHE_UPDATE} ]  || [ ! -f  ${CACHE_DIR}/supported_apps.list ]; then
Intentionally there: it allows a means to get the supported cache files updated even if all the repos and their contents are deemed up-to-date.  On an `update` we try not to call this behaviour if no repos have detected changes.  Really only useful to save having to delete the cache files (now that us used as a trigger too) or push spurious updates round the repos to trigger updating the cache.  It could be removed now that moving the tested cache file triggers a refresh.

2022-11-15 14:33 UTC, natanjunges commented on deb-get
> +    if [ ${SOMETHING} == "Changed" ] || [ ! -z ${FORCE_CACHE_UPDATE} ]  || [ ! -f  ${CACHE_DIR}/supported_apps.list ]; then
Oh I see, it's an envvar. Isn't it better to provide a command-line option for that?

2022-11-15 19:26 UTC, philclifford commented on deb-get
> +    if [ ${SOMETHING} == "Changed" ] || [ ! -z ${FORCE_CACHE_UPDATE} ]  || [ ! -f  ${CACHE_DIR}/supported_apps.list ]; then
Maybe later if/when we decide to expose it to users - I refactored the main update so it could be called directly and added as a command/option but I'm unsure yet whether there's a real use-case for normal users/situations (because it should just be an automatic self-managing feature that runs when necessary, makes life better and stays out of the way as much as possible).  I'd wait to get some more real-world-experience before deciding whether to add a command/option.

2022-11-15 21:13 UTC, natanjunges commented on deb-get
> +    if [ ${SOMETHING} == "Changed" ] || [ ! -z ${FORCE_CACHE_UPDATE} ]  || [ ! -f  ${CACHE_DIR}/supported_apps.list ]; then
Fair enough.

2022-11-15 21:14 UTC, natanjunges approved these changes

2022-11-15 21:15 UTC, merged