Add Virtualbox 7.0 and handle old list and keyfile
natanjunges/deb-get pull request #8
Opened 2022-10-17 00:48 UTC by philclifford

Hopefully I got this right, and also hoping to see the test pass as 6.1 should be installed OK then will be removed during the 7.0 install :crossed_fingers:

2022-10-17 01:01 UTC, natanjunges commented
I was actually thinking of marking `virtualbox-6.1` as deprecated, because it would be much simpler. What do you think?

2022-10-17 06:48 UTC, philclifford commented
I would leave it for a while - maybe until 7.1.  More for habit and ancient
historical pain remembered.  Also I used to work in the kind of environment
where it will be months before 7.0 is allowed so removing it here would
have  💔 .  It is that kind of customer that leads Oracle to have such odd
release naming behaviour.

On Mon, 17 Oct 2022, 02:01 Natan Junges, ***@***.***> wrote:

> I was actually thinking of marking virtualbox-6.1 as deprecated, because
> it would be much simpler. What do you think?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/natanjunges/deb-get/pull/8#issuecomment-1280123495>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACDDWY6656O7XRK6PCZJ6QLWDSQOZANCNFSM6AAAAAARGSVYT4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-17 16:55 UTC, natanjunges commented on 01-main/packages/virtualbox-7.0
> +APT_LIST_NAME=virtualbox
The same rationale applies.

2022-10-17 16:55 UTC, natanjunges commented on 01-main/packages/virtualbox-7.0
> +function postinst() {
The same rationale applies.

2022-10-18 06:27 UTC, natanjunges approved these changes

2022-10-18 06:30 UTC, natanjunges requested changes

2022-10-18 06:30 UTC, natanjunges commented on 01-main/packages/virtualbox-6.1
> -SUMMARY="VirtualBox 6.1 is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use."
The test is failing because, since it detects this file as changed, it tries to install both packages, which have the same repositories.

2022-10-18 14:11 UTC, philclifford commented on 01-main/packages/virtualbox-6.1
> -SUMMARY="VirtualBox 6.1 is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use."
Not quite: without the APT_LIST_NAME we get two lists and each has its own key, but they share the repo so apt fails because the keys "conflict".  That's why I had them aligned using the APT_LIST_NAME, which let me install 6.1 then 7.0 locally without issues, and they have just done exactly that in https://github.com/natanjunges/deb-get/actions/runs/3274012133 since I replaced APT_LIST_NAME=virtualbox in both.

2022-10-18 15:56 UTC, natanjunges commented on 01-main/packages/virtualbox-6.1
> -SUMMARY="VirtualBox 6.1 is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use."
But the solution is not that simple. If more than one package share the same repository file, when one of them is removed, so is the file, and all packages are affected. I'll have to study the documentation of `apt` to try to come up with a better solution.

2022-10-18 17:48 UTC, philclifford commented
But users will only install one virtualbox app. If they have installed 6.1
and then install 7.0 it will remove 6.1 as first step of the install if
they remove virtualbox, then removing the repo file is fine too. The only
issue I see is that we now have an entry saying 6.1 is installed by
deb-get, so maybe 7.0 postinstall function should handle that ?

On Tue, 18 Oct 2022, 16:57 Natan Junges, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In 01-main/packages/virtualbox-6.1
> <https://github.com/natanjunges/deb-get/pull/8#discussion_r998429395>:
>
> > @@ -4,4 +4,4 @@ APT_REPO_URL="https://download.virtualbox.org/virtualbox/debian ${UPSTREAM_CODEN
>  APT_REPO_OPTIONS="arch=amd64"
>  PRETTY_NAME="VirtualBox 6.1"
>  WEBSITE="https://www.virtualbox.org/"
> -SUMMARY="VirtualBox 6.1 is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use."
>
> But the solution is not that simple. If more than one package share the
> same repository file, when one of them is removed, so is the file, and all
> packages are affected. I'll have to study the documentation of apt to try
> to come up with a better solution.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/natanjunges/deb-get/pull/8#discussion_r998429395>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACDDWYZC6PH4G57EPHK5N7LWD3CFFANCNFSM6AAAAAARGSVYT4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-18 18:47 UTC, philclifford commented on 01-main/packages/virtualbox-6.1
> -SUMMARY="VirtualBox 6.1 is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use."
But users will only install one virtualbox app. If they have installed 6.1
and then install 7.0 it will remove 6.1 as first step of the install if
they remove virtualbox, then removing the repo file is fine too. The only
issue I see is that we now have an entry saying 6.1 is installed by
deb-get, so maybe 7.0 postinstall function should handle that ?

2022-10-18 22:16 UTC, natanjunges commented on 01-main/packages/virtualbox-6.1
> -SUMMARY="VirtualBox 6.1 is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use."
If users are not meant to install both of them, then failing to do so should be the correct (and simplest) behaviour. This way, `deb-get` can properly keep track of which one is installed, and nothing breaks. But a proper error message would be even better. Perhaps in the future, along with the dependency feature we are planning, a `conflicts` field could be added.

2022-10-19 00:51 UTC, philclifford commented on 01-main/packages/virtualbox-6.1
> -SUMMARY="VirtualBox 6.1 is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use."
They _cannot_ install both as they conflict/replace, but they can upgrade or downgrade (even to the Ubuntu-provided old 6.1 called just `virtualbox`).  If they ask `deb-get` for both then because we install via separate serial calls to apt-get they will get the last installed version.  I'd not prioritise implementing apt-style `conflicts` since apt already handles that anyway.

2022-10-20 00:03 UTC, philclifford commented on 01-main/packages/virtualbox-6.1
> -SUMMARY="VirtualBox 6.1 is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use."
Implementing  `replaces` and eventually handling `conflicts` sounds good.

2022-10-20 16:31 UTC, natanjunges commented on 01-main/packages/virtualbox-6.1
> -SUMMARY="VirtualBox 6.1 is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use."
OK, can you please do the requested changes, just so the tests pass and we can merge? Then we can work on those implementations.

2022-10-20 18:02 UTC, philclifford commented on 01-main/packages/virtualbox-6.1
> -SUMMARY="VirtualBox 6.1 is a general-purpose full virtualizer for x86 hardware, targeted at server, desktop and embedded use."
> OK, can you please do the requested changes, just so the tests pass and we can merge? Then we can work on those implementations.

What requested changes are outstanding ? https://github.com/natanjunges/deb-get/pull/8/commits/e97223a50d8a492969902464b18c5d3c85550a42 should have  accounted for all you asked, and  then https://github.com/natanjunges/deb-get/pull/8/commits/48d263bb5276806d8d45e15e7795264cd4f4886d put back the `APT_LIST_NAME=virtualbox` because it is needed otherwise apt finds a bogus signing key conflict when two lists and keys are present.  The push of that commit made tests pass : https://github.com/natanjunges/deb-get/actions/runs/3274012133/jobs/5386968706
(It would be good to merge the same [fix](https://github.com/wimpysworld/deb-get/pull/598) ( wimpysworld#598 ) to the same breakage on wimpysworld)

2022-10-21 03:19 UTC, natanjunges approved these changes

2022-10-21 03:21 UTC, merged